name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    name: Testing on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies 
        run: python3 -m pip install -r requirements.txt
      - name: Run tests using pytest
        run: pytest pybmrb2
      
